# ============================
# Development Stage Dockerfile
# ============================
FROM oven/bun:latest AS dev

WORKDIR /app
COPY bun.lock ./

RUN apt-get update -y && apt-get install -y openssl

WORKDIR /app/apps/server
COPY apps/server/package.json ./

RUN bun install

EXPOSE 3000

CMD ["bun", "run", "dev"]