# ============================
# Development Stage Dockerfile
# ============================
FROM oven/bun:latest AS dev

WORKDIR /app

COPY package.json bun.lock ./

RUN bun install

COPY . .

EXPOSE 3000

CMD ["bun", "run", "dev"]
