# ============================
# Development Stage Dockerfile
# ============================
FROM oven/bun:latest as dev

# Set working directory
WORKDIR /app

COPY package.json bun.lock ./

RUN bun install

COPY . .

EXPOSE 5173

CMD ["bun", "run", "dev"]
