services:
  frontend:
    image: fintrack/client:latest
    build:
      context: ..
      dockerfile: apps/client/dockerfile
      target: dev
    ports:
      - "5173:5173"
    volumes:
      - ../apps/client:/app/apps/client
      - /app/apps/client/node_modules
    working_dir: /app/apps/client
    command: bun run dev
  backend:
    image: fintrack/server:latest
    build:
      context: ..
      dockerfile: apps/server/dockerfile
      target: dev
    ports:
      - "3000:3000"
    volumes:
      - ../apps/server:/app/apps/server
      - /app/apps/server/node_modules
    working_dir: /app/apps/server
    command: >
      bash -c "bunx prisma db pull && bunx prisma generate && bun --watch server.ts"