services:
  frontend:
    image: fintrack/client:latest
    build:
      context: ..
      dockerfile: apps/client/dockerfile
      target: prod
    ports:
      - "80:80"
  backend:
    image: fintrack/server:latest
    build:
      context: ..
      dockerfile: apps/server/dockerfile
    env_file: 
      - ../apps/server/.env
    ports:
      - "3000:3000"
