services:
  frontend:
    build:
      context: ../apps/client
      dockerfile: dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ../apps/client:/app
      - /app/node_modules

  backend:
    build:
      context: ../apps/server
      dockerfile: dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ../apps/server:/app
      - /app/node_modules
